/*
 * dump_schema.js — introspect the connected Postgres and emit server/schema.sql.
 *
 * The schema of this project was never written down: it grew out of a legacy SQLite
 * file plus a pile of one-off `fix_*.js` / `add_*.js` patches. This script reads the
 * live database (READ ONLY — information_schema and pg_indexes only) and regenerates
 * a single reproducible `schema.sql` that can stand up a brand-new office database.
 *
 * Re-run it after any migration so schema.sql stays the source of truth:
 *     node server/scripts/dump_schema.js
 *
 * It never writes to the database it reads.
 */
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const fs = require('fs');
const path = require('path');
const { createPool } = require('@vercel/postgres');

const OUT = path.join(__dirname, '..', 'schema.sql');

// Tables that are pure runtime state, not structure worth recreating on a fresh office.
// (none right now — kept as the seam for when one appears)
const SKIP_TABLES = new Set([]);

const quoteIdent = (s) => (/^[a-z_][a-z0-9_]*$/.test(s) ? s : `"${s}"`);

// Render one column's DDL fragment from its information_schema row.
const columnDdl = (col) => {
    const parts = [quoteIdent(col.column_name)];

    // Serial columns come back as integer + a nextval() default; collapse them back
    // into serial/bigserial so a fresh DB gets its own sequence.
    const isSerial = col.column_default && /^nextval\(/i.test(col.column_default);
    if (isSerial) {
        parts.push(col.data_type === 'bigint' ? 'BIGSERIAL' : 'SERIAL');
    } else {
        let type = col.data_type;
        if (type === 'character varying') {
            type = col.character_maximum_length ? `VARCHAR(${col.character_maximum_length})` : 'VARCHAR';
        } else if (type === 'character') {
            type = col.character_maximum_length ? `CHAR(${col.character_maximum_length})` : 'CHAR';
        } else if (type === 'numeric' && col.numeric_precision != null) {
            type = `NUMERIC(${col.numeric_precision},${col.numeric_scale || 0})`;
        } else if (type === 'timestamp without time zone') {
            type = 'TIMESTAMP';
        } else if (type === 'timestamp with time zone') {
            type = 'TIMESTAMPTZ';
        } else if (type === 'USER-DEFINED') {
            type = col.udt_name;
        } else if (type === 'ARRAY') {
            type = `${col.udt_name.replace(/^_/, '')}[]`;
        }
        parts.push(type.toUpperCase());
        if (col.column_default != null) parts.push(`DEFAULT ${col.column_default}`);
    }

    if (col.is_nullable === 'NO' && !isSerial) parts.push('NOT NULL');
    return '    ' + parts.join(' ');
};

async function main() {
    if (!process.env.POSTGRES_URL) {
        console.error('POSTGRES_URL is not set — point it at the database you want to dump.');
        process.exit(1);
    }
    const pool = createPool({ connectionString: process.env.POSTGRES_URL });

    const { rows: tables } = await pool.query(
        `SELECT table_name FROM information_schema.tables
          WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
          ORDER BY table_name`
    );

    const { rows: columns } = await pool.query(
        `SELECT table_name, column_name, ordinal_position, column_default, is_nullable,
                data_type, character_maximum_length, numeric_precision, numeric_scale, udt_name
           FROM information_schema.columns
          WHERE table_schema = 'public'
          ORDER BY table_name, ordinal_position`
    );

    // Primary keys and unique constraints, via pg_constraint (simpler than the
    // information_schema three-way join and it keeps column order).
    const { rows: constraints } = await pool.query(
        `SELECT rel.relname   AS table_name,
                con.conname   AS name,
                con.contype   AS type,
                pg_get_constraintdef(con.oid) AS def
           FROM pg_constraint con
           JOIN pg_class rel ON rel.oid = con.conrelid
           JOIN pg_namespace ns ON ns.oid = rel.relnamespace
          WHERE ns.nspname = 'public' AND con.contype IN ('p', 'u', 'f', 'c')
          ORDER BY rel.relname, con.contype, con.conname`
    );

    const { rows: indexes } = await pool.query(
        `SELECT tablename, indexname, indexdef
           FROM pg_indexes
          WHERE schemaname = 'public'
          ORDER BY tablename, indexname`
    );

    const byTable = (rows, key = 'table_name') =>
        rows.reduce((acc, r) => { (acc[r[key]] ||= []).push(r); return acc; }, {});

    const cols = byTable(columns);
    const cons = byTable(constraints);
    const idx = byTable(indexes, 'tablename');

    const out = [];
    out.push('-- schema.sql — generated by server/scripts/dump_schema.js. Do not hand-edit;');
    out.push('-- change the database (or a migration) and re-run the dump.');
    out.push(`-- Generated: ${new Date().toISOString()}`);
    out.push('');
    out.push('-- Stands up an empty office database. Seed data (first admin, office profile,');
    out.push('-- tva_rate) is applied separately by server/scripts/provision_office.js.');
    out.push('');

    for (const { table_name: t } of tables) {
        if (SKIP_TABLES.has(t)) continue;
        const lines = (cols[t] || []).map(columnDdl);

        // Inline PK / UNIQUE / CHECK; foreign keys are emitted after all tables exist.
        for (const c of (cons[t] || []).filter((c) => c.type !== 'f')) {
            lines.push(`    CONSTRAINT ${quoteIdent(c.name)} ${c.def}`);
        }

        out.push(`CREATE TABLE IF NOT EXISTS ${quoteIdent(t)} (`);
        out.push(lines.join(',\n'));
        out.push(');');
        out.push('');
    }

    // Foreign keys last, so table creation order never matters.
    const fks = constraints.filter((c) => c.type === 'f');
    if (fks.length) {
        out.push('-- Foreign keys (emitted after all tables so creation order is irrelevant).');
        for (const c of fks) {
            out.push(
                `ALTER TABLE ${quoteIdent(c.table_name)} ADD CONSTRAINT ${quoteIdent(c.name)} ${c.def};`
            );
        }
        out.push('');
    }

    // Indexes that aren't already implied by a PK/UNIQUE constraint.
    const constraintIndexNames = new Set(constraints.map((c) => c.name));
    const extraIdx = indexes.filter((i) => !constraintIndexNames.has(i.indexname));
    if (extraIdx.length) {
        out.push('-- Indexes.');
        for (const i of extraIdx) {
            out.push(i.indexdef.replace(/^CREATE (UNIQUE )?INDEX /, 'CREATE $1INDEX IF NOT EXISTS ') + ';');
        }
        out.push('');
    }

    fs.writeFileSync(OUT, out.join('\n'), 'utf8');
    console.log(`Wrote ${OUT}`);
    console.log(`  ${tables.length} tables, ${columns.length} columns, ${fks.length} foreign keys, ${extraIdx.length} extra indexes`);
    await pool.end();
}

main().catch((e) => { console.error(e); process.exit(1); });
